require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

# desc "Set up database"
# task :db_setup do
#     drop_author_table_sql = <<-SQL
#         DROP TABLE IF EXISTS authors;
#     SQL
#     DB.execute(drop_author_table_sql)
#     author_sql = <<-SQL
#         CREATE TABLE IF NOT EXISTS authors(
#             id INTEGER PRIMARY KEY,
#             name TEXT
#         );
#     SQL
#     DB.execute(author_sql)
# end

# desc "Seed database"
# task :db_seed do
#     ruby "db/seeds.rb"
# end
